### PR TITLE
Adding a default notification template for email verification on update

### PR DESCRIPTION
**Pull request by dewniMW**
### Proposed changes in this pull request
Adds a new email template for email verification on update feature.

Related to issue: https://github.com/wso2/product-is/issues/7183

### CODE REVIEW

**Comment by somindatommy** [comment]
This PR does add only a notification template, right? Shall we update the PR description as well?

**Comment by dewniMW** [comment]
This PR is dependent on https://github.com/wso2-extensions/identity-governance/pull/349. Therefore don’t merge this PR till https://github.com/wso2-extensions/identity-governance/pull/349 is merged.

**Comment by somindatommy** [comment]
@dewniMW Change the PR title. The title should be `Adding a default notification template for email verification on update`.

**Comment by madurangasiriwardena** [comment]
@Abilashini we need to consider the data migration aspect of this PR. 
@dewniMW can you create a separate issue to track the data migration aspect?

**Comment by dewniMW** [comment]
Created issue [1] track migration changes.

[1] https://github.com/wso2/product-is/issues/7552

**Pull request merged**
